apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test
spec:
  containers:
  - name: cephrbd-rw
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/cephrbd"
      name: cephrbd
  volumes:
  - name: cephrbd
    rbd:
      monitors:
      - 18.16.44.2:6789
      user: admin
      image: ceph-rbd-test
      pool: rbd
      secretRef:
        name: ceph-client-key 
