apiVersion: v1
kind: Pod
metadata:
  name: ceph-cephfs-test
spec:
  containers:
  - name: cephfs-rw
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 18.16.44.2:6789
      user: admin
      secretRef:
        name: ceph-client-key
