---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
  namespace: ceph
  labels:
    app: ceph
    daemon: mon
spec:
  type: NodePort
  ports:
  - port: 6789
    protocol: TCP
    targetPort: 6789
    nodePort: 36789
  selector:
    app: ceph
    daemon: mon
  clusterIP: None
